### ISSUE TITLE
Wrong architecture selector

### ISSUE THREAD

**Issue by lisuml** [Mylezeem/puppet-mariadbrepo#2]
The error:

Error: No matching value for selector param 'amd64' at /etc/puppet/modules/mariadbrepo/manifests/init.pp:58 on node ubuntu1404-64-base.modeva.local
Error: No matching value for selector param 'amd64' at /etc/puppet/modules/mariadbrepo/manifests/init.pp:58 on node ubuntu1404-64-base.modeva.local

It's because puppet returns 'amd64' value instead of 'x86_64' on ubuntu 14.04 server with puppet 3.4.3 installed.

**Comment by Spredzy** [comment]
Hi @lisuml , can you test again using master.

https://github.com/Mylezeem/puppet-mariadbrepo/commit/15bdf5ec33f7095362daedcb954ca140bf800185 should fix your issue.

Please let me know if it worked.

**Comment by lisuml** [comment]
Yes, it's fixed now. Are you going to release new version on puppetlabs?

**Comment by Spredzy** [comment]
@lisuml yes, will do that later today. So you can pick it up.

**Comment by lisuml** [comment]
Thanks!

**Comment by Spredzy** [comment]
@lisuml done.

Enjoy : https://forge.puppetlabs.com/yguenane/mariadbrepo/0.2.1
